title: ~perplexedtheta
version: 1.0.0
email: jahdobble@llownd.net
description: >- # this means to ignore newlines until "baseurl:"
    "Were it so easy"
baseurl: "" # the subpath of your site, e.g. /ramblings
url: "" # the base hostname & protocol for your site, e.g. http://example.com

## Ramblings settings
paginate: 5
paginate_path: "/ramblings/:num/"
permalink: /ramblings/:year/:month/:day/:title:output_ext

# Build settings
exclude:
    - node_modules/
    - Gemfile.lock
    - LICENSE
    - package.json
    - package-lock.json
    - README.md
sass:
    style: compressed
jekyll-minifier:
    remove_spaces_inside_tags: true
    remove_multi_spaces: true
    remove_comments: true
    remove_intertag_spaces: true
    compress_css: false
    compress_javascript: true
    compress_json: true
plugins:
    - jekyll-feed
    - jekyll-minifier
